site_name: TwistMethNext
site_description: "A Nextflow pipeline for DNA methylation analysis from Twist NGS data"
site_author: JD2112
repo_url: https://github.com/JD2112/TwistMethNext
repo_name: JD2112/TwistMethNext
edit_uri: edit/main/docs/

# MkDocs theme config
theme:
  name: material
  language: en
  features:
    - navigation.instant
    - navigation.tabs
    - navigation.sections
    - search.suggest
    - search.highlight
    - toc.integrate
  palette:
    - scheme: default
      primary: blue
      accent: light blue
  logo: images/logo.svg  # Optional: if you have a logo
  favicon: images/favicon.ico  # Optional: if you have a favicon

# Plugins
plugins:
  - search
  - mike

# Markdown extensions
markdown_extensions:
  - admonition
  - codehilite
  - toc:
      permalink: true
  - pymdownx.superfences
  - pymdownx.tabbed
  - pymdownx.details
  - pymdownx.emoji
  - pymdownx.tasklist
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.keys

# Nav structure (you can expand this)
nav:
  - Home: index.md
  - Usage: usage.md
  - Configuration: config.md
  - Output: output.md
  - Changelog: changelog.md

# Where docs are located
docs_dir: docs
