site_name: TwistMethNext
site_description: A Nextflow-based DNA Methylation Data Analysis Pipeline for Twist NGS data
site_author: JD2112
repo_url: https://github.com/JD2112/TwistMethNext
edit_uri: ""

theme:
  name: material
  features:
    - navigation.instant
    - navigation.sections
    - navigation.tabs
    - search.suggest
    - search.highlight
    - toc.integrate
    - content.action.edit
    - content.code.copy
    - versioning  # ← version dropdown
  palette:
    scheme: default

plugins:
  - search
  - mike

nav:
  - Home: index.md
  - Overview: overview.md
  - Highlights: highlights.md
  - Usage:
      - Overview: usage/README.md
      - Requirements: usage/requirements.md
      - Run Command: usage/run-command.md
      - Input File: usage/input-file.md
      - Parameters Configuration: usage/parameters-configuration.md
      - Bismark Alignment: usage/bismark-alignment-with-bowtie2.md
      - Other Configurations: usage/other-configurations.md
      - Results: usage/results.md
  - Description:
      - Overview: description/README.md
      - Read Processing:
          - Overview: description/read-processing/README.md
          - FastQC: description/read-processing/fastqc.md
          - Trim Galore: description/read-processing/trim-galore.md
      - QC Reporting: description/qc-reporting.md
      - Quality Mapping: description/quality-mapping.md
      - Genome Preparation: description/genome-preparation.md
      - Bismark Analysis:
          - Overview: description/bismark-analysis/README.md
          - Alignment: description/bismark-analysis/bismark-alignment.md
          - Deduplication: description/bismark-analysis/bismark-deduplication.md
          - Methylation Extractor: description/bismark-analysis/bismark-methylation-extractor.md
          - Report: description/bismark-analysis/bismark-report.md
      - Post Processing: description/post-processing.md
      - Differential Methylation:
          - Overview: description/differential-methylation/README.md
          - edgeR: description/differential-methylation/edger.md
          - methylKit: description/differential-methylation/methylkit.md
      - Gene Ontology Analysis: description/gene-ontology-analysis.md
  - Credits: credits.md

markdown_extensions:
  - admonition
  - codehilite
  - toc:
      permalink: true
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.emoji

# extra_css:
#   - styles.css

extra:
  version:
    provider: mike
  social:
    - icon: fontawesome/solid/user
      link: https://github.com/JD2112
      name: Jyotirmoy Das
  footer: "© Jyotirmoy Das"
