site_name: TwistMethNext
site_description: A Nextflow-based DNA Methylation Data Analysis Pipeline for Twist NGS data
site_author: Jyotirmoy Das
repo_url: https://github.com/JD2112/TwistMethNext
edit_uri: ""

theme:
  name: material
  custom_dir: docs/overrides
  palette:
    primary: blue grey
    accent: blue
  font:
    text: Inter
    code: Fira Code
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.expand
    - navigation.sections
    - navigation.top
    - content.code.annotate
    - content.tabs.link
    - navigation.tabs
    - search.suggest
    - search.highlight
    - toc.integrate
    - content.action.edit
    - content.code.copy
    - versioning  # ← version dropdown

plugins:
  - search
  - mike

nav:
  - Home: index.md
  - Description: overview.md
  - Usage: usage.md
  - Credits: credits.md
  - References: references.md

markdown_extensions:
  - admonition
  - codehilite
  - toc:
      permalink: true
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.emoji

# extra_css:
#   - styles.css

extra:
  version:
    provider: mike
  current_year: !!python/object/apply:str ["2025"]

extra_css:
  - styles/extra.css

extra_javascript:
  - https://fonts.googleapis.com/css2?family=Fira+Code&family=Inter:wght@400;600&display=swap

