name: twistnext
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - python=3.9
  - nextflow=22.10.1
  - fastqc=0.11.9
  - multiqc=1.13
  - trim-galore=0.6.7
  - bismark=0.23.1
  - bowtie2=2.4.4
  - samtools=1.15
  - bedtools=2.30.0
  - r-base=4.1.0
  - bioconductor-methylkit=1.20.0
  - r-ggplot2=3.3.5
  - r-pheatmap=1.0.12
  - r-rcolorbrewer=1.1_2
  - r-reshape2=1.4.4
  - r-optparse=1.7.1